default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: programming_basics_development

test:
  <<: *default
  database: programming_basics_test

production:
  <<: *default
  database: programming_basics_production
  username: programming_basics
  url: <%= ENV["DATABASE_URL"] %>
  password: <%= ENV["PROGRAMMING_BASICS_DATABASE_PASSWORD"] %>
